src/yada/core.clj

Specifying a :header schema didn't work as intended
1. Specifying keywords (mandatory) resulted in required value not found because header keys are parsed as strings
2. Specifying (s/optional-key ...) or (s/required-key ...) is not compatible with select-keys
e.g. 
```clojure
{:header {(s/optional-key "x-user-id") s/Uuid}}
```
The solution works partially:
1. It coerces values properly
2. It allows for additional headers and they will be parsed to a String value (as before)
It does not:
1. Coerce keys. They will remain Strings.

Allow for header schema verification and coercion

---

src/yada/methods.clj

It follows the same way as PostResult to avoid this problem

GetResult now accepts a fn as response Closes #23

---

src/yada/coerce.clj

Parameter coercion (e.g. query parameter values) should be working again now.

Adds coercion of parameter values again

---

src/yada/body.clj

When using yada as a dependency in an AOT-compiled project, compilation fails with:
```
java.lang.ClassNotFoundException: clojure.core.async.impl.channels.ManyToManyChannel, compiling:(body.clj:3:1)
Exception in thread "main" java.lang.ClassNotFoundException: clojure.core.async.impl.channels.ManyToManyChannel, compiling:(body.clj:3:1)
...
```
Explicitly requiring `[clojure.core.async]` then fails with:
```
java.lang.ClassNotFoundException: manifold.stream.async.CoreAsyncSource, compiling:(body.clj:3:1)
Exception in thread "main" java.lang.ClassNotFoundException: manifold.stream.async.CoreAsyncSource, compiling:(body.clj:3:1)
...
```
AOT compilation finally succeeds if `[manifold.stream.async]` (also used in the `yada.body` import) is additionally required.

Fix AOT compilation

---

src/yada/body.clj

Fixes an issue where `'("foo" "bar")` would render as `"foobar"` instead of `["foo", "bar"]` for JSON (and other things that should be coerced to.

Include sequences for body coercions

---

src/yada/resources/classpath_resource.clj
src/yada/resources/jar_resource.clj
src/yada/resources/url_resource.clj

This is a first pass of writing a new classpath resource. I have left a few comments in the source code and commit messages. Note: I tried to write tests for the source but the classpath of `lein test` includes local file system paths and those will be different on every machine. This resource is mostly useful when running jars or uberjars.

New classpath resource

---

src/yada/request_body.clj
test/yada/process_request_body_test.clj

I noticed that when using json as the incoming content type, keyword values (not keys) were blowing up with 400. There are some built-in json coercion matchers in schema.coerce that help solve this but they weren't being used in yada so I added them.

adding schema.coerce json coercion matchers to json process-request-body

---

README.md

Add information about the dependency to `bidi` since it is required in the source, and handlers were introduced in bidi 2
https://github.com/juxt/yada/blob/fbff7d294a65d3c66a9d78d090cdfb5bdb108396/src/yada/handler.clj#L7

add information about bidi dependency

---

.gitignore
src/yada/swagger.clj
test/yada/swagger_test.clj

I have added tests for swagger spec output and removed cookie parameters from swagger output since swagger doesn't support those.
I have also changed the ```swagger-spec``` method by moving the part that generates the input for ring-swagger into its own method called ```routes->ring-swagger-spec``` and that method is what my tests check. I did this because I assume that ring-swagger works correctly when given the right input and I didn't want the test to include the whole schema to swagger thing that ring-swagger does.

Swagger tests

---

src/yada/coerce.clj
test/yada/parameters_test.clj

This adds support for having a schema as a key in resource query
parameters definition. This means that query parameters now support
defining some required and optional query parameters and then specifing
a schema that all other parameters must match.
I have also added more test cases for parse-parameters.
Fixes: #76

Support schema key in query parameters

---

src/yada/swagger.clj
test/yada/swagger_test.clj

When the bidi route had path parameters but those parameters where not defined in the resource the swagger output would have the path parameter shown in the url but would be missing the definition for the parameter. Similarly when the bidi route had qualifiers for the path parameters you couldn't even generate the swagger output. This commit fixes these issues so the swagger ouput now reflects what yada actually does when handling a request.
When no path parameters are defined for a resource yada will simply forward the path parameters from bidi directly with no check or coercion. Meaning that bidi does all the type checking and coercion and this commit will include the bidi path parameters with types in the swagger output.
But when a resource does have path parameters defined these must …

Add path parameters from bidi to swagger output

---

src/yada/schema.clj
test/yada/schema_test.clj
test/yada/statii_test.clj

While wildcard was allowed in ```get*``` the schema for responses didn't
allow it and so you couldn't use it.
There were also some corner cases in responses where the same status
could be in the key of several responses making it ambigous which
response was the correct one. So I have added a check to the schema
that requires that the keys are disjoint and so unambigous.

Support wildcard in responses schema and disallow duplicates

---

src/yada/interceptors.clj
src/yada/multipart.clj
src/yada/request_body.clj
src/yada/schema.clj

(as discussed with @mccraigmccraig)
There was no way of coercing incoming data to fit the schemas
supplied under :parameters key in resource definitions.
- optional :coercion-matchers keyword can now be added to each
method specification. The value should be a map of  keywords
to matchers (as per `schema.coerce/coercer`).
Example
{:methods {:post {:parameters {:body {:user s/Str
:created-at s/Inst}
:coercion-matchers {:body {s/Inst inst/read-instant-date}}}}}}
Things to consider:
- this change does not introduce coercion support for header params (see yada.interceptors/parse-parameters)
- I'm still not convinced about the exact placement of the :coercion-matchers map
- the supplied matcher is 'or'-ed with the hard-coded ones, which seems to me would be 
the most common case.

Custom coercion matchers in resource definitions

---

src/yada/handler.clj
test/yada/custom_error_response_test.clj

Re: https://github.com/juxt/yada/issues/55
The `500` entry in the custom responses map was not invoked for `POST` requests:
```clojure
(yada/yada
(yada/resource
{:methods
{:post {:consumes "application/json"
:produces "text/plain"
:response (fn [ctx] (throw (Exception. "Oh!")))}}
:responses
{500 {:produces "text/plain"
:response (fn [ctx] "Internal error")}}}))
```
The tests I added work, but generate some spam in the logs. Would appreciate hints on how to reduce the logging here.

invoke custom error handling for all requests

---

project.clj
src/yada/resources/webjar_resource.clj
src/yada/swagger.clj
test/yada/webjar_resource_test.clj

Webjars have a structure that means when using the normal classpath
resource you have to hardcode the version number of the webjar in the
resource name. This commit adds a webjar resource that eliminates this
problem.
This fixes #99

Add webjar resource and used it for swagger-ui

---

src/yada/interceptors.clj
src/yada/resource.clj
src/yada/resources/url_resource.clj
src/yada/security.clj
test/yada/security_test.clj

As discussed in #113, this PR adds support for the FORWARED-PROTO http header, along with a bunch of other semi-standard headers. It has been implemented as an interceptor, due to the flexibility that this brings.
Perhaps it's a good idea if we refactor this into a bigger `proxy` interceptor/module, in which we also properly handle `forwarded-by`, `forwarded-for` and `forwarded-host` headers.

Adds support for x-forwarded-proto header

---

src/yada/multipart.clj
test/yada/multipart_test.clj

As written, the parsing function for multipart content-disposition headers is a little too restrictive. As a result, when files are attached the `filename` field is omitted because the name typically includes a period character:
> content-disposition: form-data; name="file"; filename="data.csv"
Which turns into a piece which is missing the filename information:
```clojure
:content-disposition {:type "form-data", :params {"name" "file"}}
```
I added a test to exercise this case.

Relax content-disposition header regex

---

src/yada/multipart.clj
src/yada/schema.clj

Following up on #74, there's currently no way to provide custom `PartConsumer` implementations to yada to handle large multipart uploads. This change adds `:part-consumer` as a valid resource definition key, and uses it to look up the implementation to use, falling  back to the default.
A multipart-post resource could look like this now:
```clojure
(yada/resource
{:methods {:post {:summary "Uploads a file with a multipart POST"
:consumes ["multipart/form-data"]
:part-consumer (->StreamPartConsumer "/tmp/landing")
:response (fn [ctx] ...)}})
```

Allow resources to define :part-consumer for multipart uploads

---

src/yada/media_type.clj
test/yada/media_type_test.clj

I use Geoserver, which sends an accept header without a subtype, which made Yada crash (see https://github.com/juxt/yada/issues/120).
This patch fixes it, by handling "*" as a specialcase 
I've added a few tests.

Handle media-type without subtype: "*", "*; q=0.6" etc.

---

src/yada/schema.clj
src/yada/swagger.clj
src/yada/util.clj
test/yada/statii_test.clj
test/yada/swagger_test.clj

This changes the schema for method documentation responses key so that the keys now match what is allowed as keys in the resource responses key (i.e. integers, sets of integers and *) and allows namespaced keys in the methods responses values.
It also adds a merged version of the resource responses and method documentation responses to the swagger spec with * key mapped to the default swagger responses key.

Add support for responses to swagger

---

src/yada/resources/sse.clj

This change makes yada compile under Clojure 1.9.0-alpha11, in which ns forms are now spec'd

Use keyword for ns import

---

src/yada/bmh.clj

During large file uploading through-put was ~2MB/s a couple of type
hints later and we're looking at ~200MB/s.

Added type hints and explicitly boxed the recur arg

---

src/yada/request_body.clj

This is a fix for #128 
It uses the json coercer from ring-swagger instead.

extend coercion capabilities of json bodies

---

src/yada/interceptors.clj
src/yada/resource.clj
test/yada/content_encoding_test.clj

This is an attempt to fix #95 (`Content-Encoding: gzip` request header). Only gzip compression is handled at the moment. Decompression is done using a manifold future.
Resources:
* [RFC 2616 Section 14.11: Content-Encoding](https://tools.ietf.org/html/rfc2616#page-118)
* [Content-Encoding on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding)

Handle Content-Encoding header

---

src/yada/multipart.clj
src/yada/util.clj

This change allows parts of multipart requests to access the headers for the surrounding request. This can be very useful for access user access tokens present in the request headers or any other contextual information pertaining to the request as a whole that could influence the process of a part.

Assoc top level request headers into parts

---

src/yada/body.clj
src/yada/handler.clj
test/yada/custom_error_response_test.clj

Hi, this is a fix for #140, where throwing `(ex-info "..." {:status X :body Y})` in the handler fn was respecting the `:status` but `:body` was being lost.
It looks like `assoc` was the problem [on this line](https://github.com/juxt/yada/blob/e17c218f24b2ec5fd4e6dcc99e4b069046680e91/src/yada/handler.clj#L148) so I changed it to `assoc-in`, but then it was complaining about `content-length` fn not being there, so I added a bunch of `(content-length [_] nil)` which feels hacky, but works.
I added some basic tests for this too.

custom error with :body

---

doc/hello.adoc
doc/parameters.adoc
doc/resources.adoc
doc/routing.adoc

This should fix #130 - asciidoctor didn't seem to like multiple sections with similar titles or headings.

Fix links in documentation

---

src/yada/interceptors.clj

There doesn't seem to be a way to allow an optional body, i.e. allow a body with a schema, or no body at all. Declaring something like this on a method:
`{:parameters {:body (s/maybe {:foo s/Str})}}`
doesn't work, because the presence of any schema, throws a 400 [at this line](https://github.com/juxt/yada/blob/d591f9fc0b470acfa2a52cbff5d0d3b21f497e36/src/yada/interceptors.clj#L187).
@malcolmsparks we discussed this briefly on slack, and you suggested [a slightly different approach](https://clojurians-log.clojureverse.org/yada/2017-01-16.html#inst-2017-01-16T13:52:23.000710Z), the approach taken here is to just remove the check in the else clause, because schema validation further down the interceptor chain takes care of this case, and at first glance it appears we don't need to be so …

Allow optional body

---

bundles/default/test/yada/webjar_resource_test.clj
ext/webjars/src/yada/resources/webjar_resource.clj

Accessing nonexisting path in webjar resource will result in a NullPointerException because the drop-while function within the transducer `(comp (map io/resource) (drop-while nil?))` is getting called after the io/resource call.

Fix transducer ordering in new-webjar-resource

---

src/yada/test.clj
test/yada/parameters_2_test.clj
test/yada/request_for_test.clj

This handles issue #154 
~~The implementation is crude, since it uses regular expressions to get the query-string part of the uri.~~
Updated: There is actually a [`.getRawQuery`](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getRawQuery()) on `java.net.URI` instances, so the fix is to just use that instead.

correctly decode query params with request-for

---

src/yada/handler.clj

Rationale: you may already have fn (for ex. result of `(yada.handler/as-handler bidi-tree)`) which you want to pass to `aleph/listener`.

Extend HandlerCoercion protocol to handle functions

---

test/yada/custom_error_response_test.clj
test/yada/logging_test.clj
test/yada/security_test.clj
test/yada/test_util.clj

This patch turns off logging for a namespace when running tests that are expected to log errors.
The with-level macro grabs the logger for the specified namespace, sets it to the required level, executes the body, then sets it back. It's pretty gross to reach into the logging implementation to do this, but as far as I can tell, this is the best option.
This could be made a little more targeted to just a single value in the let binding, but that makes the code look a bit uglier.
http://stackoverflow.com/questions/3837801/how-to-change-root-logging-level-programmatically

Add with-level macro to silence logging for expected errors

---

ext/json/src/yada/json.clj

Decouple JSON rendering implementation from defmethod, so it can be easily overriden without copy/pasting too much.
My override now looks like this:
```
(defmethod render-map "application/json"
[m representation]
(yada-json/render-map-impl m representation {:yada.cheshire
{:escape-non-ascii true}}))
```

Decouple JSON rendering implementation

---

src/yada/security.clj
test/yada/cors_test.clj

There's a bug in the processing of `{:access-control {:allow-credentials false}}`, which is addressed in this PR. Also added some tests to verify correct behaviour.

Fixes omission of CORS header when allow-credentials is false

---

src/yada/resources/classpath_resource.clj
test/yada/classpath_resource_test.clj

This didn't work correctly from an uberjar, so reverting. But at least we have got tests now.

Revert skip-dir? in classpath resource

---

src/yada/security.clj

security-headers now has 3 behaviours in this order
1. Prefer resource-model
2. If https use default value
3. Dont assoc content-security-policy

update security-headers to correctly fetch from resource-model

---

ext/async/project.clj

Fix core.async version. It's fallen out of sync with the main project.clj for dev, this fixes it for recent clojure versions again.

Bump core.async version

---

project.clj

This is not necessary to develop the project, and is just a developer utility that should be specified by developers in their own profiles.
Found this when tracking down a pedantic override of 14->15.

Remove cider from project.clj

---

.travis.yml
project.clj
src/yada/util.clj
test/yada/methods_test.clj
test/yada/util_test.clj

[Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=446344) and old IE versions don't provide an origin header when sending POSTs. If a POST request from the same origin returns a URI, Yada returns a 201 to these browsers, instead of a 303.
With this commit, Yada now checks the referer header to determine the request's origin if the origin header is not provided.

Check referer header for same-origin? if origin not provided

---

bundles/lean/project.clj
ext/aleph/project.clj
project.clj

Use byte-streams 0.2.4-alpha4.
Byte-streams versions earlier than 0.2.4-alpha4 contains a decoding error. This is fixed in https://github.com/ztellman/byte-streams/commit/8075cdd8649251ea735a1932bb66a97812f7061b
For example the following fails in byte-streams 0.2.2, the version used in yada 1.2.10:
```!clojure
(test/is (= "å"
(bs/to-string (ByteArrayInputStream. (.getBytes "å" StandardCharsets/UTF_8))
{:chunk-size 1})))
```
So this means that UTF characters that cross the chunk boundary (default 4096 bytes) may cause incorrect decoding.
This will also fix https://github.com/juxt/yada/issues/180
Referenced libraries were also upgraded / fixed so that `treelein install` and `test` works fine.
Regards.

Use byte-streams 0.2.4-alpha4

---

src/yada/schema.clj

In the `:responses` section of a resource, `:description` was being passed
through untouched to ring-swagger, but didn't allow for the schema to be. This
is constrained by the normal output schema rules of ring-swagger, and has no
automatic validation, but is still useful.
```clojure
:responses {200 {:description "The normal response"
:schema [schema.core/Str]}}
```
solves https://github.com/juxt/yada/issues/197

Allow schemas to be passed to ring-swagger

---

ext/webjars/project.clj
project.clj

This updates jackson-databind 2.3.3 -> 2.9.4, alleviating
https://nvd.nist.gov/vuln/detail/CVE-2017-7525.

Update webjars-locator 0.32 -> 0.34

---

ext/jwt/project.clj
project.clj

This updates buddy-core 1.1.1 -> 1.4.0,
which updates org.bouncycastle/bcprov-jdk15on 1.55 -> 1.58,
alleviating CVE-2016-1000341.
See https://www.bouncycastle.org/releasenotes.html section 2.4.4, search
for CVE-2016-1000341.
This is a major version upgrade because of the following incompatible
change:
https://github.com/funcool/buddy-sign/issues/39
Please verify this does not affect yada.

Update buddy-sign 1.3.0 -> 2.2.0

---

project.clj

This updates commons-fileupload 1.3.2 -> 1.3.3, alleviating
https://nvd.nist.gov/vuln/detail/CVE-2016-1000031 .

Update ring-core 1.6.0-beta6 -> 1.6.3

---

bundles/default/test/yada/multipart_test.clj
ext/multipart/src/yada/multipart.clj

When there is a schema error in `assoc-body-params` an `error-deferred` is returned which causes a 
`ClassCastException` in the subsequent `assoc`.
Swapping the clauses of the `cond->` around fixes the problem

Fix handling of schema validation/coercion error for multipart requests

---

src/yada/media_type.clj
test/yada/media_type_test.clj

Don't throw an NPE when media-type string doesn't match pattern

---

README.md

It seems to have been pointing to the wrong URL (it showed the build status as "error" but when I clicked it the latest build was passing).

Update Travis build status image

---

src/yada/cookies.clj

https://danielcompton.net/2016/05/04/requiring-records-clojure-clojurescript
> Clojure dynamically generates the class for the record when that
namespace is required (ignoring AOT compiling). If your code never
requires the namespace that the record lives in, then it won’t be
created. This will cause ClassNotFoundException errors when you try to
import the class.
In the project this is an issue on, there is an explicit require of
yada.cookies which means that the ordering is different than the
coincidental order which works for most projects.

Require yada.context in yada.cookies

---

src/yada/util.clj

Seems like this is a rouge `(merge)` left over from somewhere?

Remove useless call to merge

---

src/yada/resources/resources_resource.clj

* No longer hard-coded to only 2 protocols: This was breaking pack's
onejar
* Handle when last modified is 0 (not known)

Fix resources_resource last-modified

---

src/yada/resource.clj

The manifold.stream.core namespace needs to be required before referencing the interface.
Fixes #271

Require manifold.stream before using Manifold's IEventSource

---

src/yada/security.clj

Exception without this patch:
❯ lein run -m clojure.main -e "(require 'yada.security)"
Exception in thread "main" java.lang.ClassNotFoundException: yada.context.Context, compiling:(yada/security.clj:1:1)

Fix use of yada.context without require

---

doc/cookies.adoc
src/yada/cookies.clj
test/yada/create_response_test.clj

Deliberately only supports explicit values for `SameSite` even though the spec allows for setting it without a value (as it defaults to "strict").
I've sorted the list of cookie attributes. As far as I can tell, RFC6265 doesn't say anything about ordering of attributes, but it does say that "Although cookies are serialized linearly in the Cookie header, servers SHOULD NOT rely upon the serialization order".
Adds a test case as well.
Fixes #265

Add support for setting "SameSite" cookie attribute

---

src/yada/interceptors.clj
src/yada/methods.clj

This hit me when I was trying to debug an exception that was getting thrown, but the stack trace stopped in yada, not in my own code where the original exception was being thrown.

Include exception cause in ex-info

---

src/yada/body.clj

This prevents potential cross site scripting attacks.

Sanitized stack trace html output on error

---

src/yada/handler.clj

No idea where this error originated from, but got an annoying exception from our prod system:
```ERROR aleph.http.server: error in HTTP handler
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
at clojure.lang.Numbers.lt(Numbers.java:226)
at clojure.lang.Numbers.lt(Numbers.java:3841)
at yada.handler$default_error_handler.invokeStatic(handler.clj:35)```
Clearly somehow we have an error whose `:status` is a `String`, which the default error handler barfs on. I'd rather have it treat this as an error and report it, so I can debug the system.

handle a non-numeric status

---

src/yada/cookies.clj
src/yada/schema.clj
test/yada/cookies_test.clj
test/yada/create_response_test.clj

* Add support for SameSite=None cookie attributes (https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7)
* Capitalise SameSite attribute values
* Expand the resource schema to handle SameSite cookies
* Set same-site cookies when they are defined in the resource
This builds off #296, so you may want to review that first. I tried to create a [stacked PR](https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/) for these two changes, but that only works if you are able to publish branches to the main repository.

Fix and improve SameSite cookie support

---

src/yada/cookies.clj
test/yada/cookies_test.clj

c69c003794d1f07336741dcd80aa7b8fa8ca5cdb added a call to `name` on the value of a cookie before encoding it. This worked on strings, symbols, and keywords, but doesn't work on numbers.
This commit fixes the bug, adds tests to exercise cookie attributes.

Support setting max-age as a number and expand cookie test coverage

---

src/yada/handler.clj
src/yada/security.clj
test/yada/cookies_test.clj
test/yada/test_util.clj

If cookies are unset by a cookie consumer (perhaps because they are
not valid), and authorization fails, the "set-cookie" header wasn't
being preserved in the error response. This means that there was no
easy way to unset a bad cookie.
This commit checks for cookies in the error handling code, and
preserves them if an exception was thrown.
It also adds a useful submap? function for testing part of the
response that we care about.

Preserve cookies after authentication failure

---

ext/multipart/src/yada/multipart.clj

As more files are added to multipart requests, the chance of file parts coming in an order that triggers the issue discussed in #291 increases. Perfect reproduction remains difficult due to the stochastic nature of this issue, but the test cases outlined in the issue should provide enough information to replicate the issue to some degree. 
All credit goes to @p-himik for finding this solution.

I291: Corrected multipart file boundary parsing.

---

doc/methods.adoc

The current sample code to require Method doesn't work because Method is a protocol.

Fix (require) syntax for Method
